### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by c-sanchez** [OpenBW/openbw#29]
Is this project alive?
Any estimated time for some public demo maybe?

**Comment by dgant** [comment]
OpenBW is fully functional for [replay viewing](http://www.openbw.com/replay-viewer/) and bot-on-bot play. [TorchCraftAI](https://torchcraft.github.io/TorchCraftAI/) uses it to run games and [CherryVis](https://torchcraft.github.io/TorchCraftAI/blog/2019/02/20/releasing-cherryvis.html) is built on top of it.

**Comment by c-sanchez** [comment]
I see, but is possible play the normal game? the campaigns?
If I'm not wrong this is a open implementation from original game, which must be compatible with the "classic" version, 1.16.1, but adding also some improvements, like support higher resolutions.
right?

And well that is my doubt, we can play the game with this engine?
Campaing? Online Mode (via alternative servers as ICCup), etc

As far as I knew the only open implementation is Stargus wich uses the Stratagus game engine, however this is in very early develeopment yet
https://github.com/Wargus/stratagus

**Comment by santiontanon** [comment]
I might be wrong, but I don't think the goal of this project was to make it so humans can play the game, but more as a tool for developing bots. So, I'm not sure that playing campaign mode was in the plans at any time. Correct me if I'm wrong though.

**Comment by luohc2004** [comment]
According to the author, this implementation lacks and needs an operation interface for human to operate in the game. The interface should deal the details in mouse move, short keys, screen moving and so on.

**Comment by dgant** [comment]
There are no plans for a human interface. There was some discussion of that prior to the announcement of StarCraft: Remastered but since then the focus has been on replay processing and AI-vs-AI play.

OpenBW continues to be regularly used as an important part of the StarCraft AI ecosystem for replay viewing and game operation. Since my earlier comment it's also been included as part of https://github.com/bmnielsen/StardustDevEnvironment for running games and integration tests.
